# Formação Cientista de Dados - DSA

## Projeto com Feedback 3 - Prevendo o Nível de Satisfação dos Clientes do Santander

### Leonardo Molero

In [101]:
# importando pacotes iniciais
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [102]:
# carregando o dados de treino
df = pd.read_csv('dados/train.csv',index_col='ID')

In [103]:
# checa o tamanho do dataframe
print(df.shape)

(76020, 370)


In [104]:
# visualiza os dados treino
df.head(10)

var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
ID                                                             
1      2     23                 0.0                      0.0   
3      2     34                 0.0                      0.0   
4      2     23                 0.0                      0.0   
8      2     37                 0.0                    195.0   
10     2     39                 0.0                      0.0   
13     2     23                 0.0                      0.0   
14     2     27                 0.0                      0.0   
18     2     26                 0.0                      0.0   
20     2     45                 0.0                      0.0   
23     2     25                 0.0                      0.0   

    imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
ID                                                                              
1                       0.0                      0.0                      0.0   
3                       0.0                      0.0                      0.0   
4                       0.0                      0.0                      0.0   
8                     195.0                      0.0                      0.0   
10                      0.0                      0.0                      0.0   
13                      0.0                      0.0                      0.0   
14                      0.0                      0.0                      0.0   
18                      0.0                      0.0                      0.0   
20                      0.0                      0.0                      0.0   
23                      0.0                      0.0                      0.0   

    imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  imp_op_var40_ult1  ...  \
ID                                                                       ...   
1                       0.0                      0.0                0.0  ...   
3                       0.0                      0.0                0.0  ...   
4                       0.0                      0.0                0.0  ...   
8                       0.0                      0.0                0.0  ...   
10                      0.0                      0.0                0.0  ...   
13                      0.0                      0.0                0.0  ...   
14                      0.0                      0.0                0.0  ...   
18                      0.0                      0.0                0.0  ...   
20                      0.0                      0.0                0.0  ...   
23                      0.0                      0.0                0.0  ...   

    saldo_medio_var33_hace2  saldo_medio_var33_hace3  saldo_medio_var33_ult1  \
ID                                                                             
1                       0.0                      0.0                     0.0   
3                       0.0                      0.0                     0.0   
4                       0.0                      0.0                     0.0   
8                       0.0                      0.0                     0.0   
10                      0.0                      0.0                     0.0   
13                      0.0                      0.0                     0.0   
14                      0.0                      0.0                     0.0   
18                      0.0                      0.0                     0.0   
20                      0.0                      0.0                     0.0   
23                      0.0                      0.0                     0.0   

    saldo_medio_var33_ult3  saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
ID                                                                             
1                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                   

In [108]:
# verifica os tipos das colunas
df.dtypes

var3                               int64
var15                              int64
imp_ent_var16_ult1               float64
imp_op_var39_comer_ult1          float64
imp_op_var39_comer_ult3          float64
imp_op_var40_comer_ult1          float64
imp_op_var40_comer_ult3          float64
imp_op_var40_efect_ult1          float64
imp_op_var40_efect_ult3          float64
imp_op_var40_ult1                float64
imp_op_var41_comer_ult1          float64
imp_op_var41_comer_ult3          float64
imp_op_var41_efect_ult1          float64
imp_op_var41_efect_ult3          float64
imp_op_var41_ult1                float64
imp_op_var39_efect_ult1          float64
imp_op_var39_efect_ult3          float64
imp_op_var39_ult1                float64
imp_sal_var16_ult1               float64
ind_var1_0                         int64
ind_var1                           int64
ind_var2_0                         int64
ind_var2                           int64
ind_var5_0                         int64
ind_var5        

In [109]:
# verifica os tipos de colunas agrupados (devido a quantidade de colunas)
df.dtypes.value_counts()

int64      259
float64    111
dtype: int64

In [110]:
# verifica estatísticas dos dados
df.describe()

var3         var15  imp_ent_var16_ult1  \
count   76020.000000  76020.000000        76020.000000   
mean    -1523.199277     33.212865           86.208265   
std     39033.462364     12.956486         1614.757313   
min   -999999.000000      5.000000            0.000000   
25%         2.000000     23.000000            0.000000   
50%         2.000000     28.000000            0.000000   
75%         2.000000     40.000000            0.000000   
max       238.000000    105.000000       210000.000000   

       imp_op_var39_comer_ult1  imp_op_var39_comer_ult3  \
count             76020.000000             76020.000000   
mean                 72.363067               119.529632   
std                 339.315831               546.266294   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max               12888.030000             21024.810000   

       imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
count             76020.000000             76020.000000   
mean                  3.559130                 6.472698   
std                  93.155749               153.737066   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max                8237.820000             11073.570000   

       imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  imp_op_var40_ult1  \
count             76020.000000             76020.000000       76020.000000   
mean                  0.412946                 0.567352           3.160715   
std                  30.604864                36.513513          95.268204   
min                   0.000000                 0.000000           0.000000   
25%                   0.000000                 0.000000           0.000000   
50%                   0.000000                 0.000000           0.000000   
75%                   0.000000                 0.000000           0.000000   
max                6600.000000              6600.000000        8237.820000   

       ...  saldo_medio_var33_hace2  saldo_medio_var33_hace3  \
count  ...             76020.000000             76020.000000   
mean   ...                 7.935824                 1.365146   
std    ...               455.887218               113.959637   
min    ...                 0.000000                 0.000000   
25%    ...                 0.000000                 0.000000   
50%    ...                 0.000000                 0.000000   
75%    ...                 0.000000                 0.000000   
max    ...             50003.880000             20385.720000   

       saldo_medio_var33_ult1  saldo_medio_var33_ult3  \
count            76020.000000            76020.000000   
mean                12.215580                8.784074   
std                783.207399              538.439211   
min                  0.000000                0.000000   
25%                  0.000000                0.000000   
50%                  0.000000                0.000000   
75%                  0.000000                0.000000   
max             138831.630000            91778.730000   

       saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
count             76020.000000             76020.000000   
mean                 31.505324                 1.858575   
std                2013.125393               147.786584   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max              438329.220000             24650.010000   

       saldo_medio_var44_ult1  saldo_medio_var44_ult3         var38  \
count            76020.000000   

In [111]:
# Distribuição da variável alvo
df.groupby('TARGET').size()

TARGET
0    73012
1     3008
dtype: int64

In [112]:
# Procura por valores nulos
df.isnull().values.any()

False

In [113]:
# Normalizar os dados

# Importação do módulo
from sklearn.preprocessing import Normalizer

# Separando o array em componentes de input e output
var = df.drop('TARGET',axis=1)
y = df['TARGET']

# Gerando os dados normalizados
scaler = Normalizer().fit(var)
normalizedVar = scaler.transform(var)

In [114]:
# Utiliza PCA para redução de dimensionalidade

# Importação do módulo
from sklearn.decomposition import PCA

# Seleção de atributos
pca = PCA(n_components = 4)
fit = pca.fit(normalizedVar)
var_reduzido = pca.fit_transform(normalizedVar)

In [115]:
X = pd.DataFrame(var_reduzido)

In [116]:
# Separação dados de treino e de teste

#Importação dos módulos
from sklearn.model_selection import train_test_split

# Separa 67% dos dados para treino
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [117]:
# Treina modelo com XGBoost 

# Importação dos módulos
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

# Criando o modelo
modelo = XGBClassifier()

# Treinando o modelo
modelo.fit(X_train, y_train)

# Pront do modelo
print(modelo)

# Fazendo previsões
y_pred = modelo.predict(X_test)
previsoes = [round(value) for value in y_pred]

# Avaliando as previsões
accuracy = accuracy_score(y_test, previsoes)
print("Acurácia: %.2f%%" % (accuracy * 100.0))

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)
Acurácia: 96.00%


# DUMP

In [32]:
# Cria função para balancar os dados (undersampling)

import math

def undersample(df, target_col, r=1):
    falses = df[target_col].value_counts()[0]
    trues = df[target_col].value_counts()[1]
    relation = float(trues)/float(falses)
    
    if trues >= r*falses:
        df_drop = df[df[target_col] == True]
        drop_size = int(math.fabs(int((relation - r) * (falses))))
    else: 
        df_drop = df[df[target_col] == False]
        drop_size = int(math.fabs(int((r-relation) * (falses))))
        
    df_drop = df_drop.sample(drop_size)
    df = df.drop(labels=df_drop.index, axis=0)
    return df

In [35]:
# verifica os dados balanceados

df2 = undersample(df, 'TARGET')
df2.groupby('TARGET').size()

TARGET
0    3008
1    3008
dtype: int64

In [71]:
# importação módulos

from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA


# Normalizando os dados
scaler = MinMaxScaler(feature_range = (0, 1))
rescaledX = scaler.fit_transform(X)

# Seleção de atributos
pca = PCA(n_components = 4)
fit = pca.fit(rescaledX)
treino_reduzido = pca.fit_transform(rescaledX)

# Sumarizando os componentes
print("Variância: %s" % fit.explained_variance_ratio_)
print(fit.components_)

Variância: [0.27154664 0.19262329 0.10112909 0.08260766]
[[ 1.73716195e-03  1.68017938e-02  4.44335017e-04 ...  9.31006583e-05
   1.09829483e-04 -3.03090629e-04]
 [-4.63170932e-04  3.44300011e-02  2.83013338e-04 ...  6.73298145e-05
   9.34273559e-05  1.90451384e-04]
 [ 6.45499373e-04  8.45067598e-02  5.17153279e-04 ...  6.43763835e-05
   9.48995703e-05  3.88831412e-04]
 [-2.35777110e-03  2.23088517e-02  1.79518139e-04 ...  5.66528078e-05
   9.63239578e-05 -4.63491861e-06]]


In [72]:
print(treino_reduzido)

[[-1.27454171  0.37597152  0.05682907 -0.43987497]
 [-0.10803772 -0.04886228  1.79918952  0.2036176 ]
 [ 0.02793549 -0.43946838 -0.33592963 -0.18787378]
 ...
 [-0.10621578 -0.3475866  -0.29509758 -0.19328765]
 [ 0.04857211 -0.43181416 -0.29590211 -0.31985864]
 [-1.27067838  0.3838911   0.076267   -0.43474395]]


In [73]:
type(treino_reduzido)

numpy.ndarray